In [1]:
import numpy as np

In [2]:
num_intervals = 4
types = np.linspace(0, 1, num_intervals+1)
step = 1 / num_intervals
types_mid = (types[:-1] + types[1:]) / 2

In [3]:
np.arange(num_intervals, 0, -1)

array([4, 3, 2, 1])

In [4]:
num_intervals
increments = np.zeros(num_intervals)
increments

array([0., 0., 0., 0.])

In [7]:
incs

NameError: name 'incs' is not defined

In [6]:
types_mid

array([0.125, 0.375, 0.625, 0.875])

In [44]:
len(types_mid)

99

In [3]:
np.linspace(0, 1, num_intervals+1)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [4]:
xs = np.linspace(0, 1, num_intervals+1)

for i in range(1, len(xs)):
    print(i)
    

1
2
3


In [5]:
 np.linspace(0, 1, num_intervals+1)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [6]:
N = 3

num_intervals = 1000

types = np.linspace(0, 1, num_intervals + 1)
step = 1 / num_intervals



In [7]:
types

array([0.   , 0.001, 0.002, ..., 0.998, 0.999, 1.   ])

In [8]:
increments = np.array([1, 0, 1, 0])

increments = np.zeros(len(types))
increments[250] = 1
increments[750] = 1


-increments[0] + np.sum((1 + 2*np.arange(num_intervals, -1, -1)) * increments)

2002.0

In [163]:
num_intervals * 2

2000

In [98]:
num_intervals * 2


6

In [85]:
stats.beta(a=20, b=20).pdf(0.5)

5.014827504783157

12

In [8]:
num_intervals = 3

for k in range(num_intervals):
    print("k", k)

k 0
k 1
k 2


In [10]:

for t in range(num_types):
    print("t", t)

t 0
t 1
t 2
t 3


In [11]:
num_types

4

In [15]:
import numpy as np

def riemann_sum_midpoint(f, a, b, n):
    """
    Compute the Riemann sum using the midpoint rule.
    
    Parameters:
    f : function
        The function to integrate
    a : float
        Lower bound of integration
    b : float
        Upper bound of integration
    n : int
        Number of subintervals
    
    Returns:
    float
        Approximation of the integral
    """
    x = np.linspace(a, b, n+1)
    dx = (b - a) / n
    x_mid = (x[:-1] + x[1:]) / 2
    return np.sum(f(x_mid) * dx)

# Example usage:
def f(x):
    return x**2

result = riemann_sum_midpoint(f, 0, 1, 1000)
print(f"Approximate integral: {result}")

Approximate integral: 0.33333325


In [19]:
n = 1000
a = 0
b = 1
x = np.linspace(a, b, n+1)

In [26]:
x_mid = (x[:-1] + x[1:]) / 2

In [21]:
dx = (b - a) / n
x_mid = (x[:-1] + x[1:]) / 2

In [22]:
x_mid

array([5.000e-04, 1.500e-03, 2.500e-03, 3.500e-03, 4.500e-03, 5.500e-03,
       6.500e-03, 7.500e-03, 8.500e-03, 9.500e-03, 1.050e-02, 1.150e-02,
       1.250e-02, 1.350e-02, 1.450e-02, 1.550e-02, 1.650e-02, 1.750e-02,
       1.850e-02, 1.950e-02, 2.050e-02, 2.150e-02, 2.250e-02, 2.350e-02,
       2.450e-02, 2.550e-02, 2.650e-02, 2.750e-02, 2.850e-02, 2.950e-02,
       3.050e-02, 3.150e-02, 3.250e-02, 3.350e-02, 3.450e-02, 3.550e-02,
       3.650e-02, 3.750e-02, 3.850e-02, 3.950e-02, 4.050e-02, 4.150e-02,
       4.250e-02, 4.350e-02, 4.450e-02, 4.550e-02, 4.650e-02, 4.750e-02,
       4.850e-02, 4.950e-02, 5.050e-02, 5.150e-02, 5.250e-02, 5.350e-02,
       5.450e-02, 5.550e-02, 5.650e-02, 5.750e-02, 5.850e-02, 5.950e-02,
       6.050e-02, 6.150e-02, 6.250e-02, 6.350e-02, 6.450e-02, 6.550e-02,
       6.650e-02, 6.750e-02, 6.850e-02, 6.950e-02, 7.050e-02, 7.150e-02,
       7.250e-02, 7.350e-02, 7.450e-02, 7.550e-02, 7.650e-02, 7.750e-02,
       7.850e-02, 7.950e-02, 8.050e-02, 8.150e-02, 